
dataset:
  camera_view_type: head # supports head only in encoding 
  dataset_size: 1 #in hours at the given hz for the base_dataset
  seed: 42 # random seed used for deterministic episode sampling
  eval_tasks: ["outfit_a_basic_toolbox"] # the task wihc shall completely included into the dataset
  exclude_eval_tasks: True # exclude the eval task from the dataset completely
  base_dataset_destination: "../base_dataset" # default is output/base_dataset, "hugging_face", "google_cloud"
  


   
