meta:
  dtype: bfloat16

model:
  hf_repo: facebook/vjepa2-vitg-fpc64-256

data:
  datasets:
    - /content/base_dataset/manifest.json
  dataset_fpcs:
    - 16
  batch_size: 1
  fps: 5
  crop_size: 256
  num_workers: 8
  persistent_workers: true
  prefetch_factor: 4
  pin_mem: true
  camera_frame: false
  state_start_idx: 0
  state_dim: 7
  action_dim: 23
  cache_parquet: false
  cache_video_readers: false

data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
    - 0.75
    - 1.35
  random_resize_scale:
    - 1.777
    - 1.777
  reprob: 0.0

output:
  local_output_dir: /content/output
  hf_repo_id: quastAI/behavior2025-vjepa2-vitg-130h-demo-embeddings
  hf_path_prefix: shards_256px_vit_16_g
  max_shard_bytes: 786432000  # 750 MiB
