
dataset:
  camera_view_type: single # single= only head camera, multi= head + left hand + right hand
  dataset_size: 1 #in hours at the given hz for the base_dataset
  eval_tasks: ["outfit_a_basic_toolbox"] # the task wihc shall completely included into the dataset
  exclude_eval_tasks: True # exclude the eval task from the dataset completely 
  include_eval_tasks_fully: False # includes all eval tasks fully then uniformly samples from all other tasks. If True exclude_eval_tasks cannot be true and all eval taks have to be fitting in the dataset_size
  obs_resolution: 256 # 256x256 RGB only support 
  fps: 5 # fps for downsampling
  shard_size: 1 # in GiB
  base_dataset_destination: None # default is output/base_dataset, "hugging_face", "google_cloud"
  encoded_dataset_destination: "hugging_face"  # "hugging_face", "google_cloud" "local (output/encoded_dataset)"
  encoded_dataset_destination_path: # TODO
  augmentation: "resize_crop" # "resize_crop" or None (no aug)
  encode_dataset: True # if false pipeline will stop after base_dataset
  



encoder:
   model_path: "/path/to/weights"
   model_name:  vit-g-16   # vit-g-16 or vit-l-16
   


   
